(define (problem problem5)
    (:domain robo-mineracao)

    (:objects
        area_1 area_2 area_3 area_4 area_5 - Area
        area_6 area_7 area_8 area_9 area_10 - Area
        area_11 area_12 area_13 area_14 area_15 - Area
        area_16 area_17 area_18 area_19 area_20 - Area
        area_21 area_22 area_23 area_24 area_25 - Area
        area_26 area_27 area_28 area_29 area_30 - Area
        area_31 area_32 area_33 area_34 area_35 - Area
        area_36 area_37 area_38 area_39 area_40 - Area
        area_41 area_42 area_43 area_44 - Area
        robo_1 - Robo
        robo_2 - Robo
        martelo - Martelo
        minerio_A minerio_B minerio_C minerio_D minerio_E - Minerio
        minerio_grande_1 minerio_grande_2 minerio_grande_3 - MinerioGrande
        elevador - Elevador
        carregador - Carregador
        extintor_incendio - ExtintorIncendio
        estacao - Estacao
    )

    (:init
        (Objeto robo_1 area_38)
        (Objeto robo_2 area_44)

        (Objeto carregador area_27)
        (Objeto estacao area_37)
        (Objeto elevador area_20)

        (Objeto minerio_A area_7)
        (Objeto minerio_B area_19)
        (Objeto minerio_C area_31)
        (Objeto minerio_D area_28)
        (Objeto minerio_E area_40)

        (Objeto minerio_grande_1 area_6)
        (Objeto minerio_grande_2 area_39)
        (Objeto minerio_grande_3 area_23)

        (Rocha_Bloqueando area_7)
        (Rocha_Bloqueando area_6)
        (Rocha_Bloqueando area_23)
        (Rocha_Bloqueando area_19)
        (Rocha_Bloqueando area_39)

        (Fogo area_31)
        (Fogo area_28)
        (Fogo area_40)

        (Objeto martelo area_29)
        (Objeto martelo area_36)
        (Objeto extintor_incendio area_35)
        (Objeto extintor_incendio area_21)

        (= (bateria-quantidade robo_1) 50)
        (= (bateria-capacidade) 100)
        (= (oleo-quantidade robo_1) 50)
        (= (oleo-capacidade) 100)

        (= (bateria-quantidade robo_2) 50)
        (= (bateria-capacidade) 100)
        (= (oleo-quantidade robo_2) 50)
        (= (oleo-capacidade) 100)

        (Tunel area_1 area_2)
        (Tunel area_1 area_4)
        (Tunel area_2 area_1)
        (Tunel area_2 area_3)
        (Tunel area_3 area_2)
        (Tunel area_3 area_5)
        (Tunel area_4 area_1)
        (Tunel area_4 area_12)
        (Tunel area_5 area_6)
        (Tunel area_5 area_3)
        (Tunel area_5 area_14)
        (Tunel area_6 area_5)
        (Tunel area_6 area_7)
        (Tunel area_7 area_6)
        (Tunel area_7 area_8)
        (Tunel area_7 area_15)
        (Tunel area_8 area_7)
        (Tunel area_8 area_9)
        (Tunel area_9 area_8)
        (Tunel area_9 area_10)
        (Tunel area_9 area_16)
        (Tunel area_10 area_9)
        (Tunel area_10 area_11)
        (Tunel area_10 area_17)
        (Tunel area_11 area_10)
        (Tunel area_12 area_13)
        (Tunel area_12 area_4)
        (Tunel area_12 area_21)
        (Tunel area_13 area_12)
        (Tunel area_13 area_14)
        (Tunel area_14 area_13)
        (Tunel area_14 area_5)
        (Tunel area_14 area_22)
        (Tunel area_15 area_7)
        (Tunel area_15 area_24)
        (Tunel area_16 area_17)
        (Tunel area_16 area_9)
        (Tunel area_16 area_26)
        (Tunel area_17 area_16)
        (Tunel area_17 area_10)
        (Tunel area_17 area_27)
        (Tunel area_18 area_19)
        (Tunel area_18 area_29)
        (Tunel area_19 area_18)
        (Tunel area_19 area_20)
        (Tunel area_19 area_30)
        (Tunel area_20 area_19)
        (Tunel area_20 area_21)
        (Tunel area_21 area_20)
        (Tunel area_21 area_12)
        (Tunel area_21 area_31)
        (Tunel area_22 area_23)
        (Tunel area_22 area_14)
        (Tunel area_22 area_33)
        (Tunel area_23 area_22)
        (Tunel area_23 area_24)
        (Tunel area_23 area_34)
        (Tunel area_24 area_23)
        (Tunel area_24 area_25)
        (Tunel area_24 area_15)
        (Tunel area_24 area_35)
        (Tunel area_25 area_24)
        (Tunel area_25 area_26)
        (Tunel area_26 area_25)
        (Tunel area_26 area_27)
        (Tunel area_26 area_16)
        (Tunel area_27 area_26)
        (Tunel area_27 area_28)
        (Tunel area_27 area_17)
        (Tunel area_28 area_27)
        (Tunel area_29 area_30)
        (Tunel area_29 area_18)
        (Tunel area_30 area_29)
        (Tunel area_30 area_19)
        (Tunel area_31 area_32)
        (Tunel area_31 area_21)
        (Tunel area_31 area_36)
        (Tunel area_32 area_31)
        (Tunel area_32 area_33)
        (Tunel area_32 area_37)
        (Tunel area_33 area_32)
        (Tunel area_33 area_34)
        (Tunel area_33 area_22)
        (Tunel area_33 area_38)
        (Tunel area_34 area_33)
        (Tunel area_34 area_35)
        (Tunel area_34 area_23)
        (Tunel area_35 area_34)
        (Tunel area_35 area_24)
        (Tunel area_36 area_37)
        (Tunel area_36 area_31)
        (Tunel area_36 area_39)
        (Tunel area_37 area_36)
        (Tunel area_37 area_38)
        (Tunel area_37 area_32)
        (Tunel area_38 area_37)
        (Tunel area_38 area_33)
        (Tunel area_38 area_40)
        (Tunel area_39 area_36)
        (Tunel area_39 area_41)
        (Tunel area_40 area_38)
        (Tunel area_40 area_43)
        (Tunel area_41 area_42)
        (Tunel area_41 area_39)
        (Tunel area_42 area_41)
        (Tunel area_42 area_43)
        (Tunel area_42 area_44)
        (Tunel area_43 area_42)
        (Tunel area_43 area_40)
        (Tunel area_44 area_42)

    )

    (:goal
        (and
            (Minerio_Extraido minerio_A)
            (Minerio_Extraido minerio_B)
            (Minerio_Extraido minerio_C)
            (Minerio_Extraido minerio_D)
            (Minerio_Extraido minerio_E)
            (MinerioGrande_Extraido minerio_grande_1)
            (MinerioGrande_Extraido minerio_grande_2)
            (MinerioGrande_Extraido minerio_grande_3)
            (not (Fogo area_31))
            (not (Fogo area_28))
            (not (Fogo area_40))
        )
    )
)